spring:
  application:
    name: notes-application
    jwtSecret: MySecretgeneratedrandomAndLongStringfortestingpurposejkiuyttrew
    jwtExpirationMs: 172800000
  security:
    user:
      name: admin
      password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/notes
    username: surya
    password: surya
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update


logging:
  level:
    org:
      springframework:
        security: DEBUG